# Generated by Django 3.0.3 on 2022-01-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_taxa_ID', models.IntegerField(db_index=True)),
                ('organism_clade_identifier', models.CharField(default='E', max_length=1)),
                ('organism_scientific_genus_name', models.CharField(max_length=256)),
                ('organism_scientific_species_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_ID', models.CharField(db_index=True, max_length=256)),
                ('pfam_family_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_ID', models.CharField(db_index=True, max_length=256)),
                ('protein_sequence', models.CharField(blank=True, max_length=256)),
                ('length_of_protein', models.IntegerField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_description', models.CharField(max_length=256)),
                ('domain_start_coordinate', models.IntegerField()),
                ('domain_end_coordinate', models.IntegerField()),
                ('domain_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Pfam')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Protein')),
            ],
        ),
    ]
