# Generated by Django 3.0.3 on 2022-01-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteindata', '0003_auto_20220120_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='protein_sequence',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
