# Generated by Django 3.0.3 on 2022-01-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteindata', '0006_domain_organism_pfam_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='organism',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='Pfam',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
