# Generated by Django 3.0.3 on 2022-01-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proteindata', '0007_auto_20220122_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_ID', models.CharField(db_index=True, max_length=256)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_ID', models.IntegerField(db_index=True)),
                ('clade', models.CharField(default='E', max_length=1)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_ID', models.CharField(db_index=True, max_length=256)),
                ('sequence', models.CharField(blank=True, max_length=700)),
                ('length', models.IntegerField()),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('pfam_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Pfam')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Protein')),
            ],
        ),
    ]
